<?php

require_once 'JsGenerator.php';

/**
 * the class for generating JavaScript for the poi
 * the generated js will be used for building the poi page
 * Class PoiJsGenerator
 */
class PoiJsGenerator implements JsGenerator
{

    private $jsString;
    private $poiData;
    private $poiCategoriesData;
    private $lang;
    private $canvasClass;
    private $callbackFunctionName;
    private $dir;
    private $rtlLangs = ['he'];

    public function __construct(string $poiData, string $poiCategoriesData, string $canvasClass = 'bmby-gallery', string $lang = 'en', string $callbackFunctionName = '')
    {
        $this->jsString = '';
        $this->poiData = $poiData;
        $this->poiCategoriesData = $poiCategoriesData;
        $this->canvasClass = $canvasClass;
        $this->lang = $lang;
        $this->callbackFunctionName = empty($callbackFunctionName) ? 'nonExistentFunction' : $callbackFunctionName ;
        $this->dir = (in_array($lang, $this->rtlLangs))?'rtl':'ltr';
        $this->setJs();
    }

    /**
     * this method is used to output javascript from php file
     * and it can be added in the html page like a regular javascript file
     */
    public function showJs()
    {
        header('Content-Type: application/javascript');
        echo $this->jsString;
    }

    /**
     * this method generates javascript string and save it to the class property so we can use it
     * and insert into the js string necessary javascript variables which are are generated by php
     */
    private function setJs()
    {
        $this->jsString = <<<EOD
// each element contains data about the certain poi
// this data is obtained from API
let poiData = $this->poiData;


// this variable contains all poi categories
let poiCategoriesData  = $this->poiCategoriesData;

const lang = '$this->lang';
const dir = '$this->dir';
let canvasClass = '$this->canvasClass';

try{
    $this->callbackFunctionName();
} catch (e) {
    if(mode === 'dev'){
        console.log('unable to run callback');
    }
}




EOD;

    }
}